import { useRouter } from 'expo-router';
import { useMemo, useState } from 'react';
import {
  Animated,
  Pressable,
  ScrollView,
  StyleSheet,
  Text,
  View,
  useWindowDimensions,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import {
  ActionItemsPanel,
  DashboardSkeleton,
  DigitalTwinBody3D,
  DigitalTwinOverviewCard,
  HealthNotificationPanel,
  OrganStatusCard,
} from '@/components/digital-twin';
import { PrimaryButton } from '@/components/PrimaryButton';
import { useHealth } from '@/context/HealthContext';
import { useEntranceAnimation } from '@/hooks/useEntranceAnimation';
import { sendDemoHealthNotification } from '@/services/notifications';
import { colors, radius, shadows, spacing } from '@/theme';

export function DigitalTwinScreen() {
  const router = useRouter();
  const { data, loading, refreshHealth } = useHealth();
  const { width } = useWindowDimensions();
  const [selectedOrganId, setSelectedOrganId] = useState<string | null>(null);

  const isWide = width >= 1024;
  const isMedium = width >= 768;
  const isCompact = width < 640;

  const heroStyle = useEntranceAnimation(80);
  const gridStyle = useEntranceAnimation(160);

  const organs = useMemo(() => data?.metrics.organs ?? {}, [data]);
  const selectedOrgan = selectedOrganId ? organs[selectedOrganId] ?? null : null;
  const notifications = useMemo(() => {
    if (!data) return [];

    const items = [];
    const { metrics } = data;

    if (metrics.overallScore < 80) {
      items.push({
        id: 'overall-score',
        level: 'info' as const,
        title: 'Overall score is below the ideal range',
        message: `Your current score is ${metrics.overallScore}. This is a demo alert that could later be generated by the chatbot.`,
        source: 'Derived from overallScore',
      });
    }

    if (metrics.vitals.heartRate < 60 || metrics.vitals.heartRate > 100) {
      items.push({
        id: 'heart-rate',
        level: 'warning' as const,
        title: 'Heart rate needs attention',
        message: `Heart rate is ${metrics.vitals.heartRate} bpm. Consider reviewing exercise, stress, and hydration.`,
        source: 'Derived from vitals.heartRate',
      });
    }

    if (metrics.vitals.oxygenLevel < 95) {
      items.push({
        id: 'oxygen',
        level: 'warning' as const,
        title: 'Oxygen level is low',
        message: `SpO2 is ${metrics.vitals.oxygenLevel}%. This is a demo notification for low readings.`,
        source: 'Derived from vitals.oxygenLevel',
      });
    }

    if (metrics.vitals.temperature > 99.5 || metrics.vitals.temperature < 97) {
      items.push({
        id: 'temperature',
        level: 'warning' as const,
        title: 'Temperature is outside the normal band',
        message: `Current temperature is ${metrics.vitals.temperature}°F. This can later trigger a chatbot alert.`,
        source: 'Derived from vitals.temperature',
      });
    }

    Object.entries(metrics.organs)
      .filter(([, organ]) => organ.status !== 'healthy')
      .slice(0, 3)
      .forEach(([key, organ]) => {
        items.push({
          id: `organ-${key}`,
          level: organ.status === 'critical' ? ('critical' as const) : ('warning' as const),
          title: `${organ.name} is showing ${organ.status} status`,
          message: `${organ.percentage}% health detected. This demo alert mirrors the kind of message a chatbot could send later.`,
          source: `Derived from organs.${key}`,
        });
      });

    if (items.length === 0) {
      items.push({
        id: 'all-clear',
        level: 'info' as const,
        title: 'No urgent alerts',
        message: 'All monitored parameters are within the demo safety range right now.',
      });
    }

    return items;
  }, [data]);

  if (!data) {
    return (
      <DashboardSkeleton
        state={loading ? 'slow' : 'offline'}
        message={
          loading
            ? 'Preparing the anatomical view while your metrics load.'
            : 'The backend is unavailable, so the detailed twin is not ready yet.'
        }
        onRetry={refreshHealth}
      />
    );
  }

  return (
    <SafeAreaView style={styles.safeArea}>
      <ScrollView
        showsVerticalScrollIndicator={false}
        bounces={false}
        contentContainerStyle={styles.scrollContent}
      >
        <View style={styles.shell}>
          <Animated.View style={[styles.header, isCompact && styles.headerCompact, heroStyle]}>
            <View style={[styles.headerLeft, isCompact && styles.headerLeftCompact]}>
              <Pressable onPress={() => router.back()} style={styles.backButton}>
                <Text style={styles.backButtonText}>← Back</Text>
              </Pressable>
              <View>
                <Text style={styles.title}>Digital Twin Anatomy</Text>
                <Text style={styles.subtitle}>Real-time organ health visualization</Text>
              </View>
            </View>

            <View style={[styles.headerRight, isCompact && styles.headerRightCompact]}>
              <View style={styles.liveBadge}>
                <View style={styles.liveDot} />
                <Text style={styles.liveText}>Live Telemetry</Text>
              </View>
            </View>
          </Animated.View>

          <View style={styles.notificationRow}>
            <HealthNotificationPanel
              notifications={notifications}
              onTriggerSystemNotification={() => void sendDemoHealthNotification(data)}
            />
          </View>

          <Animated.View
            style={[
              styles.mainGrid,
              isWide && styles.mainGridWide,
              isMedium && !isWide && styles.mainGridMedium,
              gridStyle,
            ]}
          >
            <View style={[styles.leftColumn, isCompact && styles.leftColumnCompact, isWide && styles.leftColumnWide]}>
              <DigitalTwinOverviewCard
                organs={organs}
                overallScore={data.metrics.overallScore}
              />
              <ActionItemsPanel
                recommendations={data.recommendations}
                organs={organs}
                onSelectOrgan={setSelectedOrganId}
              />
            </View>

            <View
              style={[
                styles.centerColumn,
                isCompact && styles.centerColumnCompact,
                isWide && styles.centerColumnWide,
              ]}
            >
              <DigitalTwinBody3D
                organs={organs}
                scale={isWide ? 0.85 : isCompact ? 0.64 : 0.72}
                interactive
                selectedOrganId={selectedOrganId}
                onSelectOrgan={setSelectedOrganId}
              />
            </View>

            <View
              style={[
                styles.rightColumn,
                isCompact && styles.rightColumnCompact,
                isWide && styles.rightColumnWide,
              ]}
            >
              <OrganStatusCard organ={selectedOrgan} variant="detail" />
            </View>
          </Animated.View>

          <View style={styles.footerActions}>
            <PrimaryButton title="Refresh Health Data" onPress={refreshHealth} variant="secondary" />
          </View>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: spacing.xl,
  },
  shell: {
    padding: spacing.lg,
    gap: spacing.lg,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    padding: spacing.lg,
    borderWidth: 1,
    borderColor: colors.border,
    ...shadows.card,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    flex: 1,
  },
  headerLeftCompact: {
    alignItems: 'flex-start',
    flexWrap: 'wrap',
  },
  backButton: {
    padding: spacing.sm,
  },
  backButtonText: {
    color: colors.primaryDark,
    fontSize: 14,
    fontWeight: '700',
  },
  title: {
    fontSize: 22,
    fontWeight: '900',
    color: colors.text,
  },
  subtitle: {
    fontSize: 13,
    color: colors.muted,
    marginTop: 2,
  },
  headerRight: {
    alignItems: 'flex-end',
  },
  headerRightCompact: {
    alignItems: 'flex-start',
  },
  headerCompact: {
    flexDirection: 'column',
    alignItems: 'stretch',
    gap: spacing.md,
  },
  liveBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: 999,
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.border,
  },
  liveDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.success,
  },
  liveText: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.text,
  },
  mainGrid: {
    gap: spacing.lg,
  },
  notificationRow: {
    marginBottom: spacing.sm,
  },
  mainGridWide: {
    flexDirection: 'row',
    alignItems: 'stretch',
    minHeight: 560,
  },
  mainGridMedium: {
    flexDirection: 'column',
  },
  leftColumn: {
    gap: spacing.lg,
  },
  leftColumnCompact: {
    width: '100%',
  },
  leftColumnWide: {
    flex: 3,
    minWidth: 240,
  },
  centerColumn: {
    minHeight: 480,
  },
  centerColumnCompact: {
    minHeight: 360,
  },
  centerColumnWide: {
    flex: 6,
    minWidth: 320,
  },
  rightColumn: {
    minHeight: 420,
  },
  rightColumnCompact: {
    minHeight: 360,
  },
  rightColumnWide: {
    flex: 3,
    minWidth: 260,
  },
  footerActions: {
    marginTop: spacing.sm,
  },
  loadingContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingText: {
    fontSize: 16,
    color: colors.muted,
  },
});
